{
 "title": "JMX prometheus exporter",
 "description": "Complete dashboard using metrics from prometheus JMX exporter, with drill down per release > pod",
 "tags": [ "JVM" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(jvm_memory_committed_bytes,namespace)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(jvm_memory_committed_bytes{namespace=\"$namespace\"},pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Heap used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(jvm_memory_used_bytes{area=\"heap\",namespace=~\"$namespace\"})*100) / sum(jvm_memory_max_bytes{area=\"heap\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(process_start_time_seconds{namespace=~\"$namespace\"})*1000"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jvm_info{namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\",pod_name=~\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "Used {{pod_name}}"
    },
    {
     "expr": " jvm_memory_max_bytes{area=\"heap\",pod_name=~\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "Max {{pod_name}}"
    }
   ]
  },
  {
   "title": "Non Heap",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"nonheap\",pod_name=~\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "Used  {{pod_name}}"
    }
   ]
  },
  {
   "title": "Eden Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{namespace=~\"$namespace\", id=\"Eden Space\",pod_name=~\"$pod\"}",
     "legendFormat": "Max  {{pod_name}}"
    },
    {
     "expr": "jvm_memory_used_bytes{namespace=~\"$namespace\", id=\"Eden Space\",pod_name=~\"$pod\"}",
     "legendFormat": "Used  {{pod_name}}"
    },
    {
     "expr": "jvm_memory_committed_bytes{namespace=~\"$namespace\", id=\"Eden Space\",pod_name=~\"$pod\"}",
     "legendFormat": "Committed  {{pod_name}}"
    }
   ]
  },
  {
   "title": "Tenured Gen",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{namespace=~\"$namespace\", id=\"Tenured Gen\",pod_name=~\"$pod\"}",
     "legendFormat": "Max  {{pod_name}}"
    },
    {
     "expr": "jvm_memory_used_bytes{namespace=~\"$namespace\", id=\"Tenured Gen\",pod_name=~\"$pod\"}",
     "legendFormat": "Used  {{pod_name}}"
    },
    {
     "expr": "jvm_memory_committed_bytes{namespace=~\"$namespace\", id=\"Tenured Gen\",pod_name=~\"$pod\"}",
     "legendFormat": "Committed  {{pod_name}}"
    }
   ]
  },
  {
   "title": "G1 Survivor Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{namespace=~\"$namespace\", id=\"Survivor Space\",pod_name=~\"$pod\"}",
     "legendFormat": "Max  {{pod_name}}"
    },
    {
     "expr": "jvm_memory_used_bytes{namespace=~\"$namespace\", id=\"Survivor Space\",pod_name=~\"$pod\"}",
     "legendFormat": "Used  {{pod_name}}"
    },
    {
     "expr": "jvm_memory_committed_bytes{namespace=~\"$namespace\", id=\"Survivor Space\",pod_name=~\"$pod\"}",
     "legendFormat": "Committed  {{pod_name}}"
    }
   ]
  },
  {
   "title": "Metaspace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{namespace=~\"$namespace\", id=\"Metaspace\",pod_name=~\"$pod\"}",
     "legendFormat": "Max {{pod_name}}"
    },
    {
     "expr": "jvm_memory_used_bytes{namespace=~\"$namespace\", id=\"Metaspace\",pod_name=~\"$pod\"}",
     "legendFormat": "Used {{pod_name}}"
    },
    {
     "expr": "jvm_memory_committed_bytes{namespace=~\"$namespace\", id=\"Metaspace\",pod_name=~\"$pod\"}",
     "legendFormat": "Committed {{pod_name}}"
    }
   ]
  },
  {
   "title": "Compressed Class Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{namespace=~\"$namespace\", id=\"Compressed Class Space\",pod_name=~\"$pod\"}",
     "legendFormat": "Max {{pod_name}}"
    },
    {
     "expr": "jvm_memory_used_bytes{namespace=~\"$namespace\", id=\"Compressed Class Space\",pod_name=~\"$pod\"}",
     "legendFormat": "Used {{pod_name}}"
    },
    {
     "expr": "jvm_memory_committed_bytes{namespace=~\"$namespace\", id=\"Compressed Class Space\",pod_name=~\"$pod\"}",
     "legendFormat": "Committed {{pod_name}}"
    }
   ]
  },
  {
   "title": "Code Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_max_bytes{namespace=~\"$namespace\", id=~\"CodeHeap.*\",pod_name=~\"$pod\"})by(pod_name)",
     "legendFormat": "Max {{pod_name}}"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=~\"$namespace\", id=~\"CodeHeap.*\",pod_name=~\"$pod\"})by(pod_name)",
     "legendFormat": "Used {{pod_name}}"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{namespace=~\"$namespace\", id=~\"CodeHeap.*\",pod_name=~\"$pod\"})by(pod_name)",
     "legendFormat": "Committed {{pod_name}}"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live_threads{namespace=~\"$namespace\",pod_name=~\"$pod\"}",
     "legendFormat": "JVM live threads  {{pod_name}}"
    },
    {
     "expr": "jvm_threads_daemon_threads{namespace=~\"$namespace\",pod_name=~\"$pod\"}",
     "legendFormat": "JVM daemon threads {{pod_name}}"
    },
    {
     "expr": "jvm_threads_deadlocked{namespace=~\"$namespace\",pod_name=~\"$pod\"}",
     "legendFormat": "JVM deadlocked threads  {{pod_name}}"
    }
   ]
  },
  {
   "title": "Threads Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states_threads{namespace=~\"$namespace\",pod_name=~\"$pod\",state=\"runnable\"}",
     "legendFormat": "runnable threads  {{pod_name}}"
    },
    {
     "expr": "jvm_threads_states_threads{namespace=~\"$namespace\",pod_name=~\"$pod\",state=\"terminated\"}",
     "legendFormat": "terminated threads {{pod_name}}"
    },
    {
     "expr": "jvm_threads_states_threads{namespace=~\"$namespace\",pod_name=~\"$pod\",state=\"timed-waiting\"}",
     "legendFormat": "timed-waiting threads  {{pod_name}}"
    },
    {
     "expr": "jvm_threads_states_threads{namespace=~\"$namespace\",pod_name=~\"$pod\",state=\"waiting\"}",
     "legendFormat": "waiting threads  {{pod_name}}"
    },
    {
     "expr": "jvm_threads_states_threads{namespace=~\"$namespace\",pod_name=~\"$pod\",state=\"blocked\"}",
     "legendFormat": "blocked threads  {{pod_name}}"
    },
    {
     "expr": "jvm_threads_states_threads{namespace=~\"$namespace\",pod_name=~\"$pod\",state=\"new\"}",
     "legendFormat": "new threads  {{pod_name}}"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{namespace=~\"$namespace\",pod_name=~\"$pod\"}[1m])",
     "legendFormat": "{{gc}} {{pod_name}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count{namespace=~\"$namespace\",pod_name=~\"$pod\"}[1m])",
     "legendFormat": "{{gc}}  {{pod_name}}"
    }
   ]
  },
  {
   "title": "HikariCP connection status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections{namespace=~\"$namespace\",pod_name=~\"$pod\"}",
     "legendFormat": "connections  {{pod_name}}"
    },
    {
     "expr": "hikaricp_connections_active{namespace=~\"$namespace\",pod_name=~\"$pod\"}",
     "legendFormat": "active {{pod_name}}"
    },
    {
     "expr": "hikaricp_connections_pending{namespace=~\"$namespace\",pod_name=~\"$pod\"}",
     "legendFormat": "pending{{pod_name}}"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_classes_loaded_classes{namespace=~\"$namespace\",pod_name=~\"$pod\"}[1m])",
     "legendFormat": "loaded  {{pod_name}}"
    }
   ]
  },
  {
   "title": "HikariCP connection creation / acquire time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hikaricp_connections_creation_seconds_sum{namespace=~\"$namespace\",pod_name=~\"$pod\"}[1m])",
     "legendFormat": "creation seconds {{pod_name}}"
    },
    {
     "expr": "rate(hikaricp_connections_acquire_seconds_sum{namespace=~\"$namespace\",pod_name=~\"$pod\"}[1m])",
     "legendFormat": "acquire seconds {{pod_name}}"
    }
   ]
  },
  {
   "title": "HikariCP connection time out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hikaricp_connections_timeout_total{namespace=~\"$namespace\",pod_name=~\"$pod\"}[1m])",
     "legendFormat": "timeout-total  {{pod_name}}"
    }
   ]
  }
 ]
}