{
 "title": "Node Dashborad",
 "description": "【English version】Support Node Exporter v0.16 and above.Optimize the main metrics display. Includes: CPU, memory, disk IO, network, temperature and other monitoring metrics。https://github.com/starsliao/Prometheus",
 "tags": [
  "Prometheus",
  "node_exporter",
  "StarsL.cn"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Host",
    "query": "label_values(kube_node_info, node)"
   },
   {
    "name": "node",
    "label": "IP",
    "query": "label_values(kube_node_info{node=~\"$hostname\",job=~\"node-exporter\"},instance)"
   },
   {
    "name": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{node=~\"$hostname\",fstype=~\"ext4|xfs\",job=~\"node-exporter\"}) by (mountpoint))))"
   },
   {
    "name": "env",
    "label": "环境",
    "query": "label_values(node_exporter_build_info,env)"
   },
   {
    "name": "name",
    "label": "名称",
    "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
   }
  ]
 },
 "panels": [
  { "title": "System Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds{node=~\"$hostname\",job=~\"node-exporter\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Number Of Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_info{job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Nodes Availability",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(kube_node_info{job=\"kube-state-metrics\"}) - sum(kube_node_spec_unschedulable{job=\"kube-state-metrics\"})) / sum(kube_node_info{job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Nodes Unavailable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_info{job=\"kube-state-metrics\"})",
     "legendFormat": "all_nodes"
    },
    {
     "expr": "sum (kube_node_status_condition{status=\"true\",job=\"kube-state-metrics\"})",
     "legendFormat": "node_true"
    },
    {
     "expr": "sum(kube_node_spec_unschedulable{job=\"kube-state-metrics\"})",
     "legendFormat": "node_unschedulable"
    }
   ]
  },
  {
   "title": "Node Availability",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(kube_node_info{job=\"kube-state-metrics\"}) - sum(kube_node_spec_unschedulable{job=\"kube-state-metrics\"})) / sum(kube_node_info{job=\"kube-state-metrics\"}) ",
     "legendFormat": "Node Availability"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kube_node_status_condition{status=\"true\",job=\"kube-state-metrics\",node=~\"$hostname\"})by(node)",
     "legendFormat": "node_true_{{node}}"
    },
    {
     "expr": "sum(kube_node_spec_unschedulable{job=\"kube-state-metrics\",node=~\"$hostname\"})by(node)",
     "legendFormat": "node_unschedulable_{{node}}"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Allocatable Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_pods{job=\"kube-state-metrics\",node=~\"$hostname\"}) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Capacity Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_pods{job=\"kube-state-metrics\",node=~\"$hostname\"}) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Pods Allocation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{job=\"kube-state-metrics\",node=~\"$hostname\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Pods Allocation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_info{job=\"kube-state-metrics\",node=~\"$hostname\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Pods Availability",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_info{job=\"kube-state-metrics\",node=~\"$hostname\"}) by (node) / sum(kube_node_status_allocatable_pods{job=\"kube-state-metrics\",node=~\"$hostname\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "SystemLoad", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{node=~\"$hostname\",mode='system',job=~\"node-exporter\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CPU Capacity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_cpu_cores{node=~\"$hostname\",job=~\"kube-state-metrics\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CPU-Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{node=~\"$hostname\",job=~\"kube-state-metrics\"}) by (node)",
     "legendFormat": "{{node}}-Limits"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$hostname\",job=~\"kube-state-metrics\"}) by (node)",
     "legendFormat": "{{node}}-Requests"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{node=~\"$hostname\",job=~\"node-exporter\"}",
     "legendFormat": "{{node}}_1m"
    }
   ]
  },
  {
   "title": "CPU-Total",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(avg without(cpu) (rate(node_cpu_seconds_total{node=~\"$hostname\",mode!=\"idle\",job=~\"node-exporter\"}[1m])))by(node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "System Load Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Load: $hostname",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{node=~\"$hostname\",job=~\"node-exporter\"}",
       "legendFormat": "{{node}}_1m"
      },
      {
       "expr": "node_load5{node=~\"$hostname\",job=~\"node-exporter\"}",
       "legendFormat": "{{node}}_5m"
      },
      {
       "expr": "node_load15{node=~\"$hostname\",job=~\"node-exporter\"}",
       "legendFormat": "{{node}}_15m"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Detail",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg without(cpu) (rate(node_cpu_seconds_total{node=~\"$hostname\",mode=\"system\",job=~\"node-exporter\"}[1m]))",
       "legendFormat": "System"
      },
      {
       "expr": "avg without(cpu) (rate(node_cpu_seconds_total{node=~\"$hostname\",mode=\"user\",job=~\"node-exporter\"}[1m]))",
       "legendFormat": "User"
      },
      {
       "expr": "avg without(cpu) (rate(node_cpu_seconds_total{node=~\"$hostname\",mode=\"iowait\",job=~\"node-exporter\"}[1m]))",
       "legendFormat": "iowait"
      },
      {
       "expr": "avg without(cpu) (rate(node_cpu_seconds_total{node=~\"$hostname\",mode=\"nice\",job=~\"node-exporter\"}[1m]))",
       "legendFormat": "nice"
      },
      {
       "expr": "avg without(cpu) (rate(node_cpu_seconds_total{node=~\"$hostname\",mode=\"softirq\",job=~\"node-exporter\"}[1m]))",
       "legendFormat": "softirq"
      },
      {
       "expr": "avg without(cpu) (rate(node_cpu_seconds_total{node=~\"$hostname\",mode=\"irq\",job=~\"node-exporter\"}[1m]))",
       "legendFormat": "irq"
      },
      {
       "expr": "avg without(cpu) (rate(node_cpu_seconds_total{node=~\"$hostname\",mode=\"steal\",job=~\"node-exporter\"}[1m]))",
       "legendFormat": "steal"
      }
     ]
    },
    {
     "title": "CPU Allocation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{node=~\"$hostname\",job=~\"kube-state-metrics\"})",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$hostname\",job=~\"kube-state-metrics\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(kube_node_status_allocatable_cpu_cores{node=~\"$hostname\",job=~\"kube-state-metrics\"})",
       "legendFormat": "Allocatable"
      },
      {
       "expr": "sum(avg without(cpu) (rate(node_cpu_seconds_total{node=~\"$hostname\",mode!=\"idle\",job=~\"node-exporter\"}[30m])))by(node)",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "CPU% per core",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 96 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_cpu_seconds_total{node=~\"$hostname.*\",mode!=\"idle\",job=~\"node-exporter\"}[1m]))by(cpu)",
       "legendFormat": "Usage_cpu{{cpu}}"
      }
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{node=~\"$hostname\",job=~\"node-exporter\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "RAM Capacity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_memory_bytes{node=~\"$hostname\",job=~\"kube-state-metrics\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory-Allocation",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{job=\"kube-state-metrics\"}) by (node)",
     "legendFormat": "{{node}}-Limits"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{job=\"kube-state-metrics\"}) by (node)",
     "legendFormat": "{{node}}-Requests"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node=~\"$hostname\",job=~\"node-exporter\"} - node_memory_MemAvailable_bytes{node=~\"$hostname\",job=~\"node-exporter\"}",
     "legendFormat": "{{node}}_Used"
    }
   ]
  },
  {
   "title": "Swap I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_vmstat_pswpin{node=~\"$hostname.*\",job=~\"node-exporter\"}",
     "legendFormat": "{{node}}-swpin"
    },
    {
     "expr": "node_vmstat_pswpout{node=~\"$hostname.*\",job=~\"node-exporter\"}",
     "legendFormat": "{{node}}-swpout"
    }
   ]
  },
  {
   "title": "Swap Utilization%",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - (node_memory_SwapFree_bytes{job=\"node-exporter\",node=~\"$hostname.*\"} / node_memory_SwapTotal_bytes{job=\"node-exporter\",node=~\"$hostname.*\"})) * 100",
     "legendFormat": "{{node}}-Swap%"
    }
   ]
  },
  {
   "title": "Memory Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Detail: $hostname",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 112 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{node=~\"$hostname\",job=~\"node-exporter\"} - node_memory_MemAvailable_bytes{node=~\"$hostname\",job=~\"node-exporter\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "node_memory_Buffers_bytes{node=~\"$hostname\",job=~\"node-exporter\"}",
       "legendFormat": "Buffer"
      },
      {
       "expr": "node_memory_Cached_bytes{node=~\"$hostname\",job=~\"node-exporter\"}",
       "legendFormat": "Cache"
      }
     ]
    },
    {
     "title": "Memory Allocation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 120 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{node=~\"$hostname\",job=~\"kube-state-metrics\"})",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"$hostname\",job=~\"kube-state-metrics\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(kube_node_status_allocatable_memory_bytes{node=~\"$hostname\",job=~\"kube-state-metrics\"})",
       "legendFormat": "Allocatable"
      },
      {
       "expr": "sum(node_memory_MemTotal_bytes{node=~\"$hostname\",job=~\"node-exporter\"}) - sum(node_memory_MemAvailable_bytes{node=~\"$hostname\",job=~\"node-exporter\"})",
       "legendFormat": "Used"
      }
     ]
    }
   ]
  },
  { "title": "FileSystem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 } },
  {
   "title": "FileSystem_Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{node=~\"$hostname\",job=~\"node-exporter\"}) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(1 - node_filesystem_avail_bytes{job=\"node-exporter\",node=~\"$hostname\"} / node_filesystem_size_bytes{job=\"node-exporter\",node=~\"$hostname\"}) by (node,mountpoint)",
     "legendFormat": "{{mountpoint}} : {{node}}"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{node=~\"$hostname\",job=~\"node-exporter\"} - node_filesystem_avail_bytes{node=~\"$hostname\",job=~\"node-exporter\"}) by(node,mountpoint)",
     "legendFormat": "used_{{mountpoint}}_{{node}}"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{node=~\"$hostname\",job=~\"node-exporter\"})by(node,mountpoint)",
     "legendFormat": "total_{{mountpoint}}_{{node}}"
    }
   ]
  },
  { "title": "Inodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 139 } },
  {
   "title": "Inodes: $hostname",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 140 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(node_filesystem_files{node=~\"$hostname.*\",job=~\"node-exporter\"})by(node)",
     "legendFormat": "Inodes : {{node}}"
    },
    {
     "expr": "avg(node_filesystem_files_free{node=~\"$hostname.*\",job=~\"node-exporter\"})by(node)",
     "legendFormat": "Inodes_free : {{node}}"
    }
   ]
  },
  { "title": "Disk I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 150 } },
  {
   "title": "Disk Utilization%",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 151 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{job=\"node-exporter\",node=~\"$hostname\"}[1m])",
     "legendFormat": "{{device}} : {{node}}"
    }
   ]
  },
  { "title": "Netrwork", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 160 } },
  {
   "title": "Open  File Descriptor(left)/Context switches(right)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 161 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{node=~\"$hostname\",job=~\"node-exporter\"}",
     "legendFormat": "filefd_{{node}}"
    },
    {
     "expr": "irate(node_context_switches_total{node=~\"$hostname\",job=~\"node-exporter\"}[1m])",
     "legendFormat": "switches_{{node}}"
    }
   ]
  },
  { "title": "Netstat Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 169 } },
  {
   "title": "Network Netstat",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 170 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_Tcp_CurrEstab{node=~\"$hostname\",job=~\"node-exporter\"}[1m])",
     "legendFormat": "CurrEstab : {{node}}"
    },
    {
     "expr": "rate(node_netstat_Tcp_ActiveOpens{node=~\"$hostname\",job=~\"node-exporter\"}[1m])",
     "legendFormat": "ActiveOpens : {{node}}"
    },
    {
     "expr": "rate(node_netstat_Tcp_InErrs{node=~\"$hostname\",job=~\"node-exporter\"}[1m])",
     "legendFormat": "InErrs : {{node}}"
    },
    {
     "expr": "rate(node_netstat_Tcp_InSegs{node=~\"$hostname\",job=~\"node-exporter\"}[1m])",
     "legendFormat": "InSegs : {{node}}"
    },
    {
     "expr": "rate(node_netstat_Tcp_OutSegs{node=~\"$hostname\",job=~\"node-exporter\"}[1m])",
     "legendFormat": "OutSegs : {{node}}"
    },
    {
     "expr": "rate(node_netstat_Tcp_PassiveOpens{node=~\"$hostname\",job=~\"node-exporter\"}[1m])",
     "legendFormat": "PassiveOpens : {{node}}"
    },
    {
     "expr": "rate(node_netstat_Tcp_RetransSegs{node=~\"$hostname\",job=~\"node-exporter\"}[1m])",
     "legendFormat": "RetransSegs : {{node}}"
    }
   ]
  },
  { "title": "Socket Stat Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 179 } },
  {
   "title": "Network SockStat TCP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 180 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_TCP_alloc{node=~\"$hostname\",job=~\"node-exporter\"}",
     "legendFormat": "alloc : {{node}}"
    },
    {
     "expr": "node_sockstat_TCP_inuse{node=~\"$hostname\",job=~\"node-exporter\"}",
     "legendFormat": "inuse : {{node}}"
    },
    {
     "expr": "node_sockstat_TCP_tw{node=~\"$hostname\",job=~\"node-exporter\"}",
     "legendFormat": "tw : {{node}}"
    }
   ]
  }
 ]
}