{
 "title": "Pod Detail Dashborad",
 "description": "This is for insight on important Kubernetes app metrics.\r\nWhat recources is a Pod actually using and what are it's limits or requests and what part is each container consuming?\r\nAlso has graphs for networking, disks, restarts docker images etc",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_namespace_labels, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_container_info{namespace=~\"$namespace.*\",job=~\"kube-state-metrics\"}, pod)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(kube_pod_container_info{namespace=~\"$namespace.*\",pod=~\"$pod.*\",job=~\"kube-state-metrics\"}, container)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(kube_node_info, node)"
   }
  ]
 },
 "panels": [
  { "title": "Pod Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Info: $pod",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "kube_pod_container_info{namespace=~\"$namespace.*\",pod=~\"$pod.*\",job=~\"kube-state-metrics\",job=~\"kube-state-metrics\"}"
    }
   ]
  },
  {
   "title": "Pod Availability",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace.*\",pod=~\"$pod.*\", phase=\"Running\",job=~\"kube-state-metrics\",node=~\"$node.*\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace.*\", pod=~\"$pod.*\",phase=\"Pending\",job=~\"kube-state-metrics\",node=~\"$node.*\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace.*\", pod=~\"$pod.*\", phase=\"Failed\",job=~\"kube-state-metrics\",node=~\"$node.*\"})",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace.*\", pod=~\"$pod.*\",phase=\"Unknown\",job=~\"kube-state-metrics\",node=~\"$node.*\"})",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "Pod Availability Detail",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace.*\",pod=~\"$pod.*.*\", phase=\"Running\",job=~\"kube-state-metrics\",node=~\"$node.*\"})by(pod)",
     "legendFormat": "Running-{{pod}}"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace.*\", pod=~\"$pod.*\",phase=\"Pending\",job=~\"kube-state-metrics\",node=~\"$node.*\"})by(pod)",
     "legendFormat": "Pending-{{pod}}"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace.*\", pod=~\"$pod.*\", phase=\"Failed\",job=~\"kube-state-metrics\",node=~\"$node.*\"})by(pod)",
     "legendFormat": "Failed-{{pod}}"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace.*\", pod=~\"$pod.*\",phase=\"Unknown\",job=~\"kube-state-metrics\",node=~\"$node.*\"})",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "Container Availability",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=~\"$namespace.*\", pod=~\"$pod.*\", container=~\"$container.*\",job=~\"kube-state-metrics\",node=~\"$node.*\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=~\"$namespace.*\", pod=~\"$pod.*\", container=~\"$container.*\",job=~\"kube-state-metrics\",node=~\"$node.*\"})",
     "legendFormat": "Terminated"
    },
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=~\"$namespace.*\", pod=~\"$pod.*\", container=~\"$container.*\",job=~\"kube-state-metrics\",node=~\"$node.*\"})",
     "legendFormat": "Waiting"
    },
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace.*\", pod=~\"$pod.*\", container=~\"$container.*\",job=~\"kube-state-metrics\",node=~\"$node.*\"})",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Container Availability",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=~\"$namespace.*\", pod=~\"$pod.*\", container=~\"$container.*\",job=~\"kube-state-metrics\",node=~\"$node.*\"})by(pod,container)",
     "legendFormat": "Ready_{{pod}}_{{container}}"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=~\"$namespace.*\", pod=~\"$pod.*\", container=~\"$container.*\",job=~\"kube-state-metrics\",node=~\"$node.*\"})by(pod,container)",
     "legendFormat": "Terminated_{{pod}}_{{container}}"
    },
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=~\"$namespace.*\", pod=~\"$pod.*\", container=~\"$container.*\",job=~\"kube-state-metrics\",node=~\"$node.*\"})by(pod,container)",
     "legendFormat": "Waiting_{{pod}}_{{container}}"
    },
    {
     "expr": "max(changes(kube_pod_container_status_restarts_total{namespace=~\"$namespace.*\", pod=~\"$pod.*\",job=~\"kube-state-metrics\",node=~\"$node.*\"}[1m]))by(pod)",
     "legendFormat": "Restarts_{{pod}}_{{container}}"
    }
   ]
  },
  {
   "title": "Pod / Container Unhealthy Event",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }
  },
  {
   "title": "Pod Pending / Failed / Unknown",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace.*\", pod=~\"$pod.*\",phase=\"Pending\",job=~\"kube-state-metrics\",node=~\"$node\"})by(pod)",
     "legendFormat": "Pending-{{pod}}"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace.*\", pod=~\"$pod.*\", phase=\"Failed\",job=~\"kube-state-metrics\",node=~\"$node\"})by(pod)",
     "legendFormat": "Failed-{{pod}}"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace.*\", pod=~\"$pod.*\",phase=\"Unknown\",job=~\"kube-state-metrics\",node=~\"$node\"})by(pod)",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "Container Waiting",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=~\"$namespace.*\", pod=~\"$pod.*\", container=~\"$container.*\",node=~\"$node.*\",job=~\"kube-state-metrics\"})by(pod,container)",
     "legendFormat": "Terminated_{{pod}}_{{container}}"
    }
   ]
  },
  {
   "title": "Container Terminated",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=~\"$namespace.*\", pod=~\"$pod.*\", container=~\"$container.*\",node=~\"$node.*\",job=~\"kube-state-metrics\"})by(pod,container)",
     "legendFormat": "Terminated_{{pod}}_{{container}}"
    },
    {
     "expr": "max(changes(kube_pod_container_status_restarts_total{namespace=~\"$namespace.*\", pod=~\"$pod.*\",node=~\"$node.*\",job=~\"kube-state-metrics\"}[1m]))by(pod)",
     "legendFormat": "Restarts_{{pod}}_{{container}}"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(changes(kube_pod_container_status_restarts_total{namespace=~\"$namespace.*\", pod=~\"$pod.*\",node=~\"$node.*\",job=~\"kube-state-metrics\"}[1m]))by(pod)",
     "legendFormat": "Restarts_{{pod}}_{{container}}"
    }
   ]
  },
  { "title": "Container Unhealthy Reason", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Waiting Reason",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(changes(kube_pod_container_status_waiting_reason{namespace=~\"$namespace.*\",pod=~\"$pod.*\",node=~\"$node.*\",job=~\"kube-state-metrics\"}[1m])>0)by(pod,reason,container)",
     "legendFormat": "{{pod}}_{{container}} / {{reason}}"
    }
   ]
  },
  {
   "title": "Terminated Reason",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(changes(kube_pod_container_status_terminated_reason{namespace=~\"$namespace.*\",pod=~\"$pod.*\",node=~\"$node.*\",job=~\"kube-state-metrics\"}[1m])>0)by(pod,container,reason)",
     "legendFormat": "{{pod}}_{{container}} / {{reason}}"
    }
   ]
  },
  { "title": "Pod CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "CPU: $pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{pod=~\"$pod.*\", namespace=~\"$namespace.*\",instance=~\"$node.*\",container=\"\",pod!=\"\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
     "legendFormat": "Usage: {{pod}}"
    }
   ]
  },
  {
   "title": "Throttle: $pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(container_cpu_cfs_throttled_seconds_total{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",instance=~\"$node.*\",job=~\"kubernetes-cadvisor\"}[1m]))by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "LoadAverage: $pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_load_average_10s{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",job=~\"kubernetes-cadvisor\"}[1m]))by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container Process: $pod",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(container_processes{namespace=~\"$namespace.*\",pod=~\"$pod.*\",name!=\"\",job=~\"kubernetes-cadvisor\"})by(pod,name)",
       "legendFormat": "{{pod}}_{{name}}"
      }
     ]
    },
    {
     "title": "File Descriptors: $pod",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(container_file_descriptors{namespace=~\"$namespace.*\",pod=~\"$pod.*\",name!=\"\",job=~\"kubernetes-cadvisor\"})by(pod,name)",
       "legendFormat": "{{pod}}_{{name}}"
      }
     ]
    },
    {
     "title": "CPU: $pod",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"\",job=~\"kube-state-metrics\"})",
       "legendFormat": "Requested"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace.*\",pod=~\"$pod.*\",job=~\"kube-state-metrics\"})",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace.*\",container!=\"POD\",container!=\"\",pod!=\"\", pod=~\"$pod.*\",job=~\"kubernetes-cadvisor\"}[1m]))",
       "legendFormat": "CPU"
      }
     ]
    },
    {
     "title": "CPU: $container",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 77 },
     "repeat": "container",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace.*\",container!=\"POD\",pod=~\"$pod.*\",container=\"$container\",job=~\"kube-state-metrics\"})",
       "legendFormat": "Requested"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace.*\",container!=\"POD\",pod=~\"$pod.*\",container=\"$container\",job=~\"kube-state-metrics\"})",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace.*\",container!=\"POD\",container!=\"\",pod!=\"\", pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m]))",
       "legendFormat": "Usage"
      }
     ]
    },
    {
     "title": "CPU: $container",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace.*\",container!=\"POD\",pod=~\"$pod.*\",container=\"$container\",job=~\"kube-state-metrics\"})",
       "legendFormat": "Requested"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace.*\",container!=\"POD\",pod=~\"$pod.*\",container=\"$container\",job=~\"kube-state-metrics\"})",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace.*\",container!=\"POD\",container!=\"\",pod!=\"\", pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m]))",
       "legendFormat": "Usage"
      }
     ]
    },
    {
     "title": "CPU: $container",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace.*\",container!=\"POD\",pod=~\"$pod.*\",container=\"$container\",job=~\"kube-state-metrics\"})",
       "legendFormat": "Requested"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace.*\",container!=\"POD\",pod=~\"$pod.*\",container=\"$container\",job=~\"kube-state-metrics\"})",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace.*\",container!=\"POD\",container!=\"\",pod!=\"\", pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m]))",
       "legendFormat": "Usage"
      }
     ]
    },
    {
     "title": "CPU: $container",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace.*\",container!=\"POD\",pod=~\"$pod.*\",container=\"$container\",job=~\"kube-state-metrics\"})",
       "legendFormat": "Requested"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace.*\",container!=\"POD\",pod=~\"$pod.*\",container=\"$container\",job=~\"kube-state-metrics\"})",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace.*\",container!=\"POD\",container!=\"\",pod!=\"\", pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m]))",
       "legendFormat": "Usage"
      }
     ]
    },
    {
     "title": "CPU: $container",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 86 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace.*\",container!=\"POD\",pod=~\"$pod.*\",container=\"$container\",job=~\"kube-state-metrics\"})",
       "legendFormat": "Requested"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace.*\",container!=\"POD\",pod=~\"$pod.*\",container=\"$container\",job=~\"kube-state-metrics\"})",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace.*\",container!=\"POD\",container!=\"\",pod!=\"\", pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m]))",
       "legendFormat": "Usage"
      }
     ]
    },
    {
     "title": "CPU: $container",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 86 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace.*\",container!=\"POD\",pod=~\"$pod.*\",container=\"$container\",job=~\"kube-state-metrics\"})",
       "legendFormat": "Requested"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace.*\",container!=\"POD\",pod=~\"$pod.*\",container=\"$container\",job=~\"kube-state-metrics\"})",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace.*\",container!=\"POD\",container!=\"\",pod!=\"\", pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m]))",
       "legendFormat": "Usage"
      }
     ]
    },
    {
     "title": "CPU: $container",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 86 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace.*\",container!=\"POD\",pod=~\"$pod.*\",container=\"$container\",job=~\"kube-state-metrics\"})",
       "legendFormat": "Requested"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace.*\",container!=\"POD\",pod=~\"$pod.*\",container=\"$container\",job=~\"kube-state-metrics\"})",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace.*\",container!=\"POD\",container!=\"\",pod!=\"\", pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m]))",
       "legendFormat": "Usage"
      }
     ]
    }
   ]
  },
  {
   "title": "Container Throttle",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throttle: $container",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 96 },
     "repeat": "container",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_cpu_cfs_throttled_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=~\"$container.*\",job=~\"kubernetes-cadvisor\"}[1m]))by(pod,container)",
       "legendFormat": "{{pod}}_{{container}}"
      }
     ]
    },
    {
     "title": "Throttle: $container",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 96 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_cpu_cfs_throttled_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=~\"$container.*\",job=~\"kubernetes-cadvisor\"}[1m]))by(pod,container)",
       "legendFormat": "{{pod}}_{{container}}"
      }
     ]
    },
    {
     "title": "Throttle: $container",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 96 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_cpu_cfs_throttled_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=~\"$container.*\",job=~\"kubernetes-cadvisor\"}[1m]))by(pod,container)",
       "legendFormat": "{{pod}}_{{container}}"
      }
     ]
    },
    {
     "title": "Throttle: $container",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 96 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_cpu_cfs_throttled_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=~\"$container.*\",job=~\"kubernetes-cadvisor\"}[1m]))by(pod,container)",
       "legendFormat": "{{pod}}_{{container}}"
      }
     ]
    },
    {
     "title": "Throttle: $container",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 102 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_cpu_cfs_throttled_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=~\"$container.*\",job=~\"kubernetes-cadvisor\"}[1m]))by(pod,container)",
       "legendFormat": "{{pod}}_{{container}}"
      }
     ]
    },
    {
     "title": "Throttle: $container",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 102 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_cpu_cfs_throttled_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=~\"$container.*\",job=~\"kubernetes-cadvisor\"}[1m]))by(pod,container)",
       "legendFormat": "{{pod}}_{{container}}"
      }
     ]
    },
    {
     "title": "Throttle: $container",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 102 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_cpu_cfs_throttled_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=~\"$container.*\",job=~\"kubernetes-cadvisor\"}[1m]))by(pod,container)",
       "legendFormat": "{{pod}}_{{container}}"
      }
     ]
    }
   ]
  },
  { "title": "Pod Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Memory: $pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",container!=\"\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}) by (pod)",
     "legendFormat": "Working Set_{{pod}}"
    }
   ]
  },
  {
   "title": "Swap Usage: $pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_swap{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",job=~\"kubernetes-cadvisor\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Failure Count: $pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg (irate(container_memory_failcnt{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
     "legendFormat": "failcnt_{{pod}}"
    }
   ]
  },
  {
   "title": "Container Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory: $pod",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 122 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace.*\",pod=~\"$pod.*\",job=~\"kube-state-metrics\"})",
       "legendFormat": "Requested"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace.*\",pod=~\"$pod.*\",job=~\"kube-state-metrics\"})",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace.*\",container!=\"POD\",container!=\"\",pod!=\"\", pod=~\"$pod.*\",job=~\"kubernetes-cadvisor\"})",
       "legendFormat": "MEM"
      },
      {}
     ]
    },
    {
     "title": "Memory: $container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 130 },
     "repeat": "container",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=~\"$container\",job=~\"kube-state-metrics\"})",
       "legendFormat": "Requested"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=~\"$container\",job=~\"kube-state-metrics\"})",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace.*\",container!=\"POD\",container!=\"\",pod!=\"\", pod=~\"$pod.*\",container=~\"$container\",job=~\"kubernetes-cadvisor\"}) by (container)",
       "legendFormat": "Usage: {{ container }}"
      }
     ]
    },
    {
     "title": "Memory: $container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 130 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=~\"$container\",job=~\"kube-state-metrics\"})",
       "legendFormat": "Requested"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=~\"$container\",job=~\"kube-state-metrics\"})",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace.*\",container!=\"POD\",container!=\"\",pod!=\"\", pod=~\"$pod.*\",container=~\"$container\",job=~\"kubernetes-cadvisor\"}) by (container)",
       "legendFormat": "Usage: {{ container }}"
      }
     ]
    },
    {
     "title": "Memory: $container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 130 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=~\"$container\",job=~\"kube-state-metrics\"})",
       "legendFormat": "Requested"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=~\"$container\",job=~\"kube-state-metrics\"})",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace.*\",container!=\"POD\",container!=\"\",pod!=\"\", pod=~\"$pod.*\",container=~\"$container\",job=~\"kubernetes-cadvisor\"}) by (container)",
       "legendFormat": "Usage: {{ container }}"
      }
     ]
    },
    {
     "title": "Memory: $container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 130 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=~\"$container\",job=~\"kube-state-metrics\"})",
       "legendFormat": "Requested"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=~\"$container\",job=~\"kube-state-metrics\"})",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace.*\",container!=\"POD\",container!=\"\",pod!=\"\", pod=~\"$pod.*\",container=~\"$container\",job=~\"kubernetes-cadvisor\"}) by (container)",
       "legendFormat": "Usage: {{ container }}"
      }
     ]
    },
    {
     "title": "Memory: $container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 137 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=~\"$container\",job=~\"kube-state-metrics\"})",
       "legendFormat": "Requested"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=~\"$container\",job=~\"kube-state-metrics\"})",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace.*\",container!=\"POD\",container!=\"\",pod!=\"\", pod=~\"$pod.*\",container=~\"$container\",job=~\"kubernetes-cadvisor\"}) by (container)",
       "legendFormat": "Usage: {{ container }}"
      }
     ]
    },
    {
     "title": "Memory: $container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 137 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=~\"$container\",job=~\"kube-state-metrics\"})",
       "legendFormat": "Requested"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=~\"$container\",job=~\"kube-state-metrics\"})",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace.*\",container!=\"POD\",container!=\"\",pod!=\"\", pod=~\"$pod.*\",container=~\"$container\",job=~\"kubernetes-cadvisor\"}) by (container)",
       "legendFormat": "Usage: {{ container }}"
      }
     ]
    },
    {
     "title": "Memory: $container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 137 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=~\"$container\",job=~\"kube-state-metrics\"})",
       "legendFormat": "Requested"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=~\"$container\",job=~\"kube-state-metrics\"})",
       "legendFormat": "Limits"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace.*\",container!=\"POD\",container!=\"\",pod!=\"\", pod=~\"$pod.*\",container=~\"$container\",job=~\"kubernetes-cadvisor\"}) by (container)",
       "legendFormat": "Usage: {{ container }}"
      }
     ]
    },
    {
     "title": "Swap Usage: $container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 137 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_swap{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",job=~\"kubernetes-cadvisor\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Swap Usage: $container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 144 },
     "repeat": "container",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_swap{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",job=~\"kubernetes-cadvisor\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Swap Usage: $container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 144 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_swap{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",job=~\"kubernetes-cadvisor\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Swap Usage: $container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 144 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_swap{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",job=~\"kubernetes-cadvisor\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Swap Usage: $container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 151 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_swap{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",job=~\"kubernetes-cadvisor\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Swap Usage: $container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 151 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_swap{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",job=~\"kubernetes-cadvisor\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Swap Usage: $container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 151 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_swap{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",job=~\"kubernetes-cadvisor\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Container Memory Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 135 },
     "repeat": "container",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",container=\"$container\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}) by (pod)",
       "legendFormat": "Working Set_{{pod}}"
      },
      {
       "expr": "sum (container_memory_cache{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",container=\"$container\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}) by (pod)",
       "legendFormat": "Cache_{{pod}}"
      },
      {
       "expr": "sum(container_memory_rss{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",container=\"$container\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}) by (pod)",
       "legendFormat": "RSS_{{pod}}"
      },
      {
       "expr": "sum(container_memory_mapped_file{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",container=\"$container\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}) by (pod)",
       "legendFormat": "Mapped File_{{pod}}"
      }
     ]
    },
    {
     "title": "Memory: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 135 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",container=\"$container\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}) by (pod)",
       "legendFormat": "Working Set_{{pod}}"
      },
      {
       "expr": "sum (container_memory_cache{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",container=\"$container\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}) by (pod)",
       "legendFormat": "Cache_{{pod}}"
      },
      {
       "expr": "sum(container_memory_rss{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",container=\"$container\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}) by (pod)",
       "legendFormat": "RSS_{{pod}}"
      },
      {
       "expr": "sum(container_memory_mapped_file{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",container=\"$container\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}) by (pod)",
       "legendFormat": "Mapped File_{{pod}}"
      }
     ]
    },
    {
     "title": "Memory: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 135 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",container=\"$container\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}) by (pod)",
       "legendFormat": "Working Set_{{pod}}"
      },
      {
       "expr": "sum (container_memory_cache{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",container=\"$container\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}) by (pod)",
       "legendFormat": "Cache_{{pod}}"
      },
      {
       "expr": "sum(container_memory_rss{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",container=\"$container\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}) by (pod)",
       "legendFormat": "RSS_{{pod}}"
      },
      {
       "expr": "sum(container_memory_mapped_file{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",container=\"$container\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}) by (pod)",
       "legendFormat": "Mapped File_{{pod}}"
      }
     ]
    },
    {
     "title": "Memory: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 143 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",container=\"$container\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}) by (pod)",
       "legendFormat": "Working Set_{{pod}}"
      },
      {
       "expr": "sum (container_memory_cache{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",container=\"$container\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}) by (pod)",
       "legendFormat": "Cache_{{pod}}"
      },
      {
       "expr": "sum(container_memory_rss{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",container=\"$container\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}) by (pod)",
       "legendFormat": "RSS_{{pod}}"
      },
      {
       "expr": "sum(container_memory_mapped_file{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",container=\"$container\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}) by (pod)",
       "legendFormat": "Mapped File_{{pod}}"
      }
     ]
    },
    {
     "title": "Memory: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 143 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",container=\"$container\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}) by (pod)",
       "legendFormat": "Working Set_{{pod}}"
      },
      {
       "expr": "sum (container_memory_cache{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",container=\"$container\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}) by (pod)",
       "legendFormat": "Cache_{{pod}}"
      },
      {
       "expr": "sum(container_memory_rss{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",container=\"$container\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}) by (pod)",
       "legendFormat": "RSS_{{pod}}"
      },
      {
       "expr": "sum(container_memory_mapped_file{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",container=\"$container\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}) by (pod)",
       "legendFormat": "Mapped File_{{pod}}"
      }
     ]
    },
    {
     "title": "Memory: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 143 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",container=\"$container\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}) by (pod)",
       "legendFormat": "Working Set_{{pod}}"
      },
      {
       "expr": "sum (container_memory_cache{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",container=\"$container\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}) by (pod)",
       "legendFormat": "Cache_{{pod}}"
      },
      {
       "expr": "sum(container_memory_rss{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",container=\"$container\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}) by (pod)",
       "legendFormat": "RSS_{{pod}}"
      },
      {
       "expr": "sum(container_memory_mapped_file{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",container=\"$container\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}) by (pod)",
       "legendFormat": "Mapped File_{{pod}}"
      }
     ]
    },
    {
     "title": "Memory: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 151 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",container=\"$container\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}) by (pod)",
       "legendFormat": "Working Set_{{pod}}"
      },
      {
       "expr": "sum (container_memory_cache{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",container=\"$container\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}) by (pod)",
       "legendFormat": "Cache_{{pod}}"
      },
      {
       "expr": "sum(container_memory_rss{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",container=\"$container\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}) by (pod)",
       "legendFormat": "RSS_{{pod}}"
      },
      {
       "expr": "sum(container_memory_mapped_file{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",container=\"$container\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}) by (pod)",
       "legendFormat": "Mapped File_{{pod}}"
      }
     ]
    }
   ]
  },
  { "title": "Pod File System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{namespace=~\"$namespace.*\",pod=~\"$pod.*\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"})by(device,pod,name)",
     "legendFormat": "usage : {{device}} : {{name}} : {{pod}}"
    }
   ]
  },
  {
   "title": "Inodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_inodes_free{namespace=~\"$namespace.*\",pod=~\"$pod.*\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"})by(pod)",
     "legendFormat": "free : {{pod}}"
    },
    {
     "expr": "sum(container_fs_inodes_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"})by(pod)",
     "legendFormat": "total : {{pod}}"
    }
   ]
  },
  { "title": "Pod Disk I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 } },
  {
   "title": "Disk Utilization%",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_io_time_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk R/W Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 131 },
   "yaxes": [
    { "format": "decbytes", "label": "read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_fs_reads_bytes_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}[1m])) by (pod)",
     "legendFormat": "read : {{pod}}"
    },
    {
     "expr": "avg(irate(container_fs_writes_bytes_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}[1m])) by (pod)",
     "legendFormat": "write : {{pod}}"
    }
   ]
  },
  {
   "title": "Disk R/W IO Completed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 138 },
   "yaxes": [
    { "format": "short", "label": "read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_fs_reads_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",job=~\"kubernetes-cadvisor\",instance=~\"$node\"}[1m])) by (pod)",
     "legendFormat": "read : {{pod}}"
    },
    {
     "expr": "avg(irate(container_fs_writes_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",job=~\"kubernetes-cadvisor\",instance=~\"$node\"}[1m])) by (pod)",
     "legendFormat": "write : {{pod}}"
    }
   ]
  },
  {
   "title": "Disk R/W latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 145 },
   "yaxes": [
    { "format": "s", "label": "Time. read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_fs_read_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",job=~\"kubernetes-cadvisor\",instance=~\"$node\"}[1m])) by (pod)",
     "legendFormat": "read : {{pod}}"
    },
    {
     "expr": "avg(irate(container_fs_write_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",job=~\"kubernetes-cadvisor\",instance=~\"$node\"}[1m])) by (pod)",
     "legendFormat": "write : {{pod}}"
    }
   ]
  },
  {
   "title": "Disk avgqu-sz",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 152 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_fs_io_time_weighted_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",job=~\"kubernetes-cadvisor\",instance=~\"$node\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container Disk I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 158 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Utilization%: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 142 },
     "repeat": "container",
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_fs_io_time_seconds_total{namespace=~\"$namespace.*\",container!=\"POD\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Disk Utilization%: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 142 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_fs_io_time_seconds_total{namespace=~\"$namespace.*\",container!=\"POD\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Disk Utilization%: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 142 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_fs_io_time_seconds_total{namespace=~\"$namespace.*\",container!=\"POD\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Disk Utilization%: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 142 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_fs_io_time_seconds_total{namespace=~\"$namespace.*\",container!=\"POD\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Disk Utilization%: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 150 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_fs_io_time_seconds_total{namespace=~\"$namespace.*\",container!=\"POD\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Disk Utilization%: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 150 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_fs_io_time_seconds_total{namespace=~\"$namespace.*\",container!=\"POD\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Disk Utilization%: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 150 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_fs_io_time_seconds_total{namespace=~\"$namespace.*\",container!=\"POD\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Disk R/W Bytes: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 150 },
     "yaxes": [
      { "format": "decbytes", "label": "read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_reads_bytes_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      },
      {
       "expr": "avg(irate(container_fs_writes_bytes_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-write"
      }
     ]
    },
    {
     "title": "Disk R/W Bytes: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 158 },
     "repeat": "container",
     "yaxes": [
      { "format": "decbytes", "label": "read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_reads_bytes_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      },
      {
       "expr": "avg(irate(container_fs_writes_bytes_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-write"
      }
     ]
    },
    {
     "title": "Disk R/W Bytes: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 158 },
     "yaxes": [
      { "format": "decbytes", "label": "read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_reads_bytes_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      },
      {
       "expr": "avg(irate(container_fs_writes_bytes_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-write"
      }
     ]
    },
    {
     "title": "Disk R/W Bytes: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 158 },
     "yaxes": [
      { "format": "decbytes", "label": "read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_reads_bytes_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      },
      {
       "expr": "avg(irate(container_fs_writes_bytes_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-write"
      }
     ]
    },
    {
     "title": "Disk R/W IO Completed: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 158 },
     "yaxes": [
      { "format": "short", "label": "read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_reads_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      },
      {
       "expr": "avg(irate(container_fs_writes_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-write"
      }
     ]
    },
    {
     "title": "Disk R/W Bytes: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 166 },
     "yaxes": [
      { "format": "decbytes", "label": "read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_reads_bytes_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      },
      {
       "expr": "avg(irate(container_fs_writes_bytes_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-write"
      }
     ]
    },
    {
     "title": "Disk R/W Bytes: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 166 },
     "yaxes": [
      { "format": "decbytes", "label": "read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_reads_bytes_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      },
      {
       "expr": "avg(irate(container_fs_writes_bytes_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-write"
      }
     ]
    },
    {
     "title": "Disk R/W Bytes: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 166 },
     "yaxes": [
      { "format": "decbytes", "label": "read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_reads_bytes_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      },
      {
       "expr": "avg(irate(container_fs_writes_bytes_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-write"
      }
     ]
    },
    {
     "title": "Disk R/W latency: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 166 },
     "yaxes": [
      { "format": "s", "label": "Time. read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_read_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      },
      {
       "expr": "avg(irate(container_fs_write_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-write"
      }
     ]
    },
    {
     "title": "Disk R/W IO Completed: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 174 },
     "repeat": "container",
     "yaxes": [
      { "format": "short", "label": "read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_reads_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      },
      {
       "expr": "avg(irate(container_fs_writes_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-write"
      }
     ]
    },
    {
     "title": "Disk R/W IO Completed: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 174 },
     "yaxes": [
      { "format": "short", "label": "read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_reads_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      },
      {
       "expr": "avg(irate(container_fs_writes_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-write"
      }
     ]
    },
    {
     "title": "Disk R/W IO Completed: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 174 },
     "yaxes": [
      { "format": "short", "label": "read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_reads_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      },
      {
       "expr": "avg(irate(container_fs_writes_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-write"
      }
     ]
    },
    {
     "title": "Disk avgqu-sz: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 174 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_io_time_weighted_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      }
     ]
    },
    {
     "title": "Disk R/W IO Completed: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 182 },
     "yaxes": [
      { "format": "short", "label": "read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_reads_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      },
      {
       "expr": "avg(irate(container_fs_writes_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-write"
      }
     ]
    },
    {
     "title": "Disk R/W IO Completed: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 182 },
     "yaxes": [
      { "format": "short", "label": "read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_reads_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      },
      {
       "expr": "avg(irate(container_fs_writes_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-write"
      }
     ]
    },
    {
     "title": "Disk R/W IO Completed: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 182 },
     "yaxes": [
      { "format": "short", "label": "read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_reads_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      },
      {
       "expr": "avg(irate(container_fs_writes_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-write"
      }
     ]
    },
    {
     "title": "Disk R/W latency: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 190 },
     "repeat": "container",
     "yaxes": [
      { "format": "s", "label": "Time. read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_read_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      },
      {
       "expr": "avg(irate(container_fs_write_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-write"
      }
     ]
    },
    {
     "title": "Disk R/W latency: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 190 },
     "yaxes": [
      { "format": "s", "label": "Time. read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_read_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      },
      {
       "expr": "avg(irate(container_fs_write_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-write"
      }
     ]
    },
    {
     "title": "Disk R/W latency: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 190 },
     "yaxes": [
      { "format": "s", "label": "Time. read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_read_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      },
      {
       "expr": "avg(irate(container_fs_write_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-write"
      }
     ]
    },
    {
     "title": "Disk R/W latency: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 198 },
     "yaxes": [
      { "format": "s", "label": "Time. read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_read_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      },
      {
       "expr": "avg(irate(container_fs_write_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-write"
      }
     ]
    },
    {
     "title": "Disk R/W latency: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 198 },
     "yaxes": [
      { "format": "s", "label": "Time. read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_read_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      },
      {
       "expr": "avg(irate(container_fs_write_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-write"
      }
     ]
    },
    {
     "title": "Disk R/W latency: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 198 },
     "yaxes": [
      { "format": "s", "label": "Time. read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_read_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      },
      {
       "expr": "avg(irate(container_fs_write_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-write"
      }
     ]
    },
    {
     "title": "Disk avgqu-sz: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 206 },
     "repeat": "container",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_io_time_weighted_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      }
     ]
    },
    {
     "title": "Disk avgqu-sz: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 206 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_io_time_weighted_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      }
     ]
    },
    {
     "title": "Disk avgqu-sz: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 206 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_io_time_weighted_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      }
     ]
    },
    {
     "title": "Disk avgqu-sz: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 214 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_io_time_weighted_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      }
     ]
    },
    {
     "title": "Disk avgqu-sz: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 214 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_io_time_weighted_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      }
     ]
    },
    {
     "title": "Disk avgqu-sz: $container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 214 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(irate(container_fs_io_time_weighted_seconds_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",container=\"$container\",job=~\"kubernetes-cadvisor\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}-read"
      }
     ]
    }
   ]
  },
  { "title": "Pod Network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 159 } },
  {
   "title": "Network Traffic Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 160 },
   "yaxes": [
    { "format": "decbytes", "label": "Receive (-) / transmit (+)" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_network_receive_bytes_total{pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}[1m])) by (pod)",
     "legendFormat": "Receive_{{pod}}_bytes"
    },
    {
     "expr": "avg(irate(container_network_transmit_bytes_total{pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}[1m])) by (pod)",
     "legendFormat": "Transmit_{{pod}}_bytes"
    }
   ]
  },
  {
   "title": "Network Traffics: $pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 168 },
   "yaxes": [
    { "format": "short", "label": "Receive (-) / transmit (+)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}[1m]))by(pod)",
     "legendFormat": "Receive_{{pod}}"
    },
    {
     "expr": "sum(rate(container_network_transmit_packets_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}[1m]))by(pod)",
     "legendFormat": "Transmit_{{pod}}"
    }
   ]
  },
  {
   "title": "Network-Dropped: $pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 176 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}[1m]))",
     "legendFormat": "Receive-Dropped"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}[1m]))",
     "legendFormat": "Transmit-Dropped"
    }
   ]
  },
  {
   "title": "Network-Errors: $pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 183 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_errors_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}[1m]))",
     "legendFormat": "Receive-Errors"
    },
    {
     "expr": "sum(irate(container_network_transmit_errors_total{namespace=~\"$namespace.*\",pod=~\"$pod.*\",job=~\"kubernetes-cadvisor\",instance=~\"$node.*\"}[1m]))",
     "legendFormat": "Transmit-Errors"
    }
   ]
  }
 ]
}